sudo: required
dist: trusty
services: docker
language: cpp
python:
- '3.4'
cache:
- pip
- apt
addons:
  apt:
    packages:
    - git
    - python3
    - python3-pip
jobs:
  include:
  - stage: say hello world
    if: tag =~ ^v
    os: linux
    script:
    - echo "Hello world"
